language: nix
sudo: required
services:
  - docker
script: nix-build dockerimage.nix
before_deploy:
    - export DOCKER_USERNAME=$DOCKER_USERNAME
    - export DOCKER_PASSWORD=$DOCKER_PASSWORD
deploy:
    skip_cleanup: true
    provider: script
    script: sh deploy-docker-hub.sh
